spring:
    application:
        name: auth-service

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}
                    jwk-set-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

    mail:
        host: ${MAIL_SERVER:localhost}
        port: 1025
        username: magnat
        password: pass
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enabled: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: 6379
            database: 0
            timeout: 5000
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 4
                    min-idle: 1


server:
    port: 8025

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka/

app:
    config:
        keycloak:
            server-url: http://${KEYCLOAK_SERVER:localhost:8080}
            realm: magnat-api-realm
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            logout-endpoint: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/logout
            token-endpoint: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
